In [324]:
# Clone repo if data is on githib
#!rm -r machine-learning/  # first remove folder, if present
#!git clone https://github.com/joneikholmkea/machine-learning  # replace with your Github account

In [325]:
# imports go here
import pandas as pd

In [326]:
pd.set_option('display.max_columns', None) # print all columns. Pandas truncate if too many columns
df = pd.read_csv('/Users/cemakay/Data/breast-cancer-wisconsin-data_data.csv')
df.tail()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
564  926424         M        21.56         22.39          142.00     1479.0   
565  926682         M        20.13         28.25          131.20     1261.0   
566  926954         M        16.60         28.08          108.30      858.1   
567  927241         M        20.60         29.33          140.10     1265.0   
568   92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  fractal_dimension_mean  radius_se  texture_se  \
564         0.1726                 0.05623     1.1760       1.256   
565         0.1752                 0.05533     0.7655       2.463   
566         0.1590                 0.05648     0.4564       1.075   
567         0.2397                 0.07016     0.7260       1.595   
568         0.1587                 0.05884     0.3857       1.428   

     perimeter_se  area_se  smoothness_se  compactness_se  concavity_se  \
564         7.673   158.70       0.010300         0.02891       0.05198   
565         5.203    99.04       0.005769         0.02423       0.03950   
566         3.425    48.55       0.005903         0.03731       0.04730   
567         5.772    86.22       0.006522         0.06158       0.07117   
568         2.548    19.15       0.007189         0.00466       0.00000   

     concave points_se  symmetry_se  fractal_dimension_se  radius_worst  \
564            0.02454      0.01114              0.004239        25.450   
565            0.01678      0.01898              0.002498        23.690   
566            0.01557      0.01318              0.003892        18.980   
567            0.01664      0.02324              0.006185        25.740   
568            0.00000      0.02676              0.002783         9.456   

     texture_worst  perimeter_worst  area_worst  smoothness_worst  \
564          26.40           166.10      2027.0           0.14100   
565          38.25           155.00      1731.0           0.11660   
566          34.12           126.70      1124.0           0.11390   
567          39.42           184.60      1821.0           0.16500   
568          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
564                  0.07115          NaN  
565                  0.06637          NaN  
566                  0.07820          NaN  
567                  0.12400          NaN  
568                  0.07039          NaN

In [327]:
# 1. Preprocess data  
#df.isnull().sum()
df.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [328]:
# Excluding also last column 'Unnamed: 32' with only NaN values. 
# Drop column before dropping rows with dropna() if one column only has NaN.
X = df.drop(columns=['id', 'diagnosis', 'Unnamed: 32']) # include all columns except 'id' and 'diagnosis'. They dont mean anything for the model
X = X.values # convert from Pandas dataframe to numpy array
X.shape

(569, 30)

In [329]:
#df.dropna(inplace=True) # handle missing data(remove)

In [330]:
# Scale data
# Only use this, if the data is outside -10.0 … 10.0 (as a rule of thumb)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)
X

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [331]:
y = df.iloc[: , 1] # Target column 'diagnosis at index 1
y = y.map({'M': 1, 'B': 0}) # Encode categorical data to binaries
counts = y.value_counts()
print(counts)
y = y.values # convert from Pandas dataframe to numpy array


# Capital X and lower-case y comes from Linear Algebra. 
# The input is often a 2D array (matrix, named X) while the output is often a 1D array (vector, named y)

diagnosis
0    357
1    212
Name: count, dtype: int64


In [332]:
# 2. Split the data
#After preprocessing, split your dataset into two parts: a training set and a testing set.
#An 80:20 split is a common choice, where 80% of the data is used for training the model, and the remaining 20% is used for evaluating its performance.
#You can use functions like train_test_split from scikit-learn to achieve this

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X[:-2],y[:-2],test_size=0.2, random_state=42)

In [333]:
lastY = y[-2:]
lastY

array([1, 0])

In [334]:
lastX = X[-2:]
lastX

array([[ 1.83834103,  2.33645719,  1.98252415,  1.73521799,  1.52576706,
         3.27214378,  3.296944  ,  2.65886573,  2.13719425,  1.04369542,
         1.15793543,  0.68608793,  1.43852964,  1.0095027 , -0.17299998,
         2.01771639,  1.30228464,  0.78572138,  0.32663363,  0.90405707,
         1.96123934,  2.23792588,  2.30360062,  1.65317077,  1.43042677,
         3.90484795,  3.19760468,  2.28998549,  1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, -1.34778924, -3.11208479,
        -1.15075248, -1.11487284, -1.26181958, -0.8200699 , -0.56103238,
        -0.07027874,  0.3830925 , -0.15744905, -0.46615196,  0.04934236,
        -1.16351619, -1.05750068, -1.91344745,  0.75282996, -0.382754  ,
        -1.41089258,  0.76418957, -1.43273495, -1.07581292, -1.85901852,
        -1.2075525 , -1.30583065, -1.74506282, -0.04813821, -0.75120669]])

In [335]:
# 3. Select/Create a  Classification Model
# Choose a machine learning model suitable for classification tasks.
# Common choices include: 
# Logistic Regression: it is used for binary classification
# Decision Trees:
# Random Forests:
# Support Vector Machines (SVM): works well for both linear and nonlinear classification tasks
# Gradient Boosting Models

# Instantiate and fit the model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

# 4. Training the Model
#Fit the chosen model on the training data.
model.fit(X_train, y_train)

LogisticRegression()

In [336]:
# 5. Evaluating the model's performance on the test set
#After training, evaluate the model's performance using the testing data.
#Common evaluation metrics for classification tasks include accuracy, precision, recall, F1-score, and ROC-AUC.
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)
print('Accuracy:', accuracy)

Accuracy: 0.9736842105263158


In [337]:
# 6. Prediction: 
#Once you're satisfied with the model's performance, you can use it to make predictions on new data.
model.fit(lastX, lastY)
newY = model.predict(lastX)


print('True diagnosis: ', *lastY)
print('Predicted diagnosis: ', *newY)
print('Correct prediction?: ', *lastY == newY)

True diagnosis:  1 0
Predicted diagnosis:  1 0
Correct prediction?:  True True
